// lib/i18n/locales/admin-en/adminProfile.ts
//
// Traductions ANGLAISES du namespace admin `adminProfile`.
//
// La SOURCE DE VERITE est le francais (`../admin-fr/adminProfile.ts`) : toute cle
// ajoutee la-bas doit l'etre ici avec exactement la meme structure, sans quoi
// le garde-fou de compilation `../admin-parity.ts` casse le typecheck.
//
// Ne PAS annoter `as const` : la parite se verifie contre le francais, dont
// les valeurs sont de type `string` — des types litteraux la feraient echouer.

export default {
  pageTitle: 'Admin – My profile',
  breadcrumbStaff: 'Staff area',
  breadcrumbCurrent: 'My profile',
  heading: 'My profile',
  subtitle: 'Summary of your staff account.',
  avatarAlt: 'Avatar',
  logout: 'Log out',
  tabProfile: 'Profile',
  tabSecurity: 'Security',
  tabPrivacy: 'Privacy',
  emailLabel: 'Email',
  roleLabel: 'Staff role',
  createdAtLabel: 'Profile created on',
  staffIdLabel: 'Staff ID',
  editHeading: 'Edit my profile',
  displayNameLabel: 'Display name',
  displayNamePlaceholder: 'Your staff handle',
  avatarUrlLabel: 'Avatar (URL)',
  avatarHelp: 'Optional. Leave empty to remove the avatar.',
  saving: 'Saving…',
  save: 'Save',
  emailHeading: 'Change my email',
  newEmailLabel: 'New email',
  emailSending: 'Sending…',
  emailSubmit: 'Change my email',
  emailConfirmNote: 'A confirmation email will be sent to your new address.',
  passwordHeading: 'Change my password',
  newPasswordLabel: 'New password',
  confirmPasswordLabel: 'Confirm password',
  passwordChanging: 'Changing…',
  passwordSubmit: 'Change my password',
  passwordHelp: 'Minimum 8 characters.',
  dataHeading: 'My data',
  exporting: 'Exporting…',
  exportBtn: 'Download my data',
  exportHelp:
    'Retrieve all your personal information in JSON format (GDPR right of access).',
  deleteBtn: 'Delete my account',
  deleteHelp:
    'GDPR right to be forgotten — your account and all your data will be permanently deleted.',
  systemHeading: 'System information',
  userIdLabel: 'User ID',
  deleteDialogTitle: 'Delete my account',
  deleteDialogSubtitle: 'GDPR right to be forgotten',
  deleteConfirmLabel: 'Confirm deletion',
  deleteConfirmingLabel: 'Deleting…',
  cancelLabel: 'Cancel',
  deleteDialogBodyBefore: 'This action is ',
  deleteDialogBodyStrong: 'irreversible',
  deleteDialogBodyAfter:
    '. All your data, your staff role, and your memberships will be permanently deleted.',
  defaultDisplayName: 'Staff profile',
  toastEmailSent:
    'A confirmation email has been sent to your new address. Click the link to complete the change.',
  errorEmailChange: 'Error while changing email.',
  errorPasswordTooShort: 'The password must be at least 8 characters.',
  errorPasswordMismatch: "The passwords don't match.",
  toastPasswordChanged: 'Your password was changed successfully.',
  errorPasswordChange: 'Error while changing password.',
  toastProfileUpdated: 'Profile updated.',
  errorExport: 'Error during export.',
  errorDelete: 'Error during deletion.',
  errorUnexpected: 'Unexpected error',
  battlenetHeading: 'Verify my BattleTag',
  twitchHeading: 'My Twitch account',
  discordHeading: 'My Discord account',
  tcgHeading: 'My collectible card',
  mfaHeading: 'Two-factor authentication (TOTP)',
  mfaIntro:
    'Protect your staff account with a 6-digit code generated by an authenticator app (Google Authenticator, 1Password, Aegis…).',
  mfaInvite:
    'Recommended: turn on two-factor authentication. It may become mandatory to access the admin area.',
  mfaStatusOn: 'On',
  mfaStatusOff: 'Off',
  mfaEnableBtn: 'Turn on two-factor authentication',
  mfaScanQr: 'Scan this QR code with your app, then enter the code it shows.',
  mfaQrAlt: 'TOTP enrollment QR code',
  mfaSecretLabel: 'Or enter this key manually',
  mfaCodeLabel: '6-digit code',
  mfaVerifyBtn: 'Verify and turn on',
  mfaVerifying: 'Verifying…',
  mfaCancelBtn: 'Cancel',
  mfaChallengeIntro:
    'Enter the code from your authenticator app to verify this session.',
  mfaChallengeBtn: 'Verify',
  mfaSessionVerified: 'This session is verified by your second factor.',
  mfaDisableBtn: 'Turn off',
  mfaDisableHelp:
    'Turning off two-factor authentication requires a session verified with a code.',
  toastMfaEnabled: 'Two-factor authentication turned on.',
  toastMfaVerified: 'Session verified.',
  toastMfaDisabled: 'Two-factor authentication turned off.',
  errorMfaCode: 'Invalid code. Try again with the code currently shown.',
  errorMfaGeneric: 'Two-factor authentication error.',
  mfaPageTitle: "Two-factor authentication | OW Women's Cup",
  mfaPageBadge: 'Security',
  mfaPageHeading: 'Two-factor authentication',
  mfaPageEnforcedIntro:
    'Access to the admin area requires a second factor. Turn it on or enter your code to continue.',
  mfaPageOptionalIntro:
    'The second factor is not mandatory yet, but it protects your account starting today.',
  mfaPageContinue: 'Continue to the admin area',
  mfaPageLogout: 'Sign out',
};
