/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import { useState } from 'react';
import Head from 'next/head';
import { useMediaQuery } from 'react-responsive';
import Header from '../components/Header/header';
import Sponsors from '../components/Sponsors/sponsors';
import About from '../components/About/about';
import Tickets from '../components/Tickets/tickets';
import Heading from '../components/Typography/heading';
import Paragraph from '../components/Typography/paragraph';
import Subscription from '../components/Form/subscription';
import Speaker from '../components/Speaker/speaker';
import cities from '../config/city-lists.json';
import teams from '../config/teams.json';
import speakers from '../config/speakers.json';
import Link from 'next/link';
import Button from '../components/Buttons/button';
import Dropdown from '../components/Dropdown/dropdown';
import { City } from '../types/types';
import Popup from '../components/Popup/popup';

function encode(data: Record<string, string>) {
  return new URLSearchParams(data).toString();
}

export default function Home() {
  const isTablet = useMediaQuery({ maxWidth: '1118px' });
  const [speakersList, setSpeakersList] = useState(speakers);
  const [teamsList, setTeamsList] = useState(teams);
  const [currentCity, setCurrentCity] = useState<Partial<City>>({
    name: 'All',
  });

  const handleSpeakers = (city: string) => {
    if (city && city !== 'all') {
      const citySpeaker = speakers.filter((speaker) =>
        speaker.city.includes(city)
      );
      setSpeakersList(citySpeaker);
    } else if (city === 'all') {
      setSpeakersList(speakers);
    } else {
      setSpeakersList([]);
    }
  };

  const handleTeams = (city: string) => {
    if (city && city !== 'all') {
      const cityTeam = teams.filter((team) => team.city.includes(city));
      setTeamsList(cityTeam);
    } else if (city === 'all') {
      setTeamsList(teams);
    } else {
      setTeamsList([]);
    }
  };

  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState<null | 'ok' | 'err'>(null);
  const [errMsg, setErrMsg] = useState('');

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setSending(true);
    setSent(null);
    setErrMsg('');

    const form = e.currentTarget;
    const formData = new FormData(form);
    // IMPORTANT: Netlify a besoin du champ "form-name" dans le body
    const payload: Record<string, string> = {
      'form-name': (form.getAttribute('name') as string) || 'contact',
    };
    formData.forEach((value, key) => (payload[key] = String(value)));

    try {
      const res = await fetch('/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: encode(payload),
      });
      if (res.ok) {
        form.reset();
        setSent('ok');
      } else {
        setSent('err');
        setErrMsg('Soumission non acceptée.');
      }
    } catch (err: any) {
      setSent('err');
      setErrMsg('Erreur réseau.');
    } finally {
      setSending(false);
    }
  }

  return (
    <div>
      <Head>
        <title>OW WOMEN'S CUP 2025</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        src="/img/illustra.png"
        className="color-effect"
        alt="background-illustration"
      />
      <Header />
      {/* <Popup /> */}
      <div id="about" className="mt-20">
        <About />
      </div>
      <div id="register" className="container mt-20 lg:mt-0">
        <div className="flex items-center flex-col justify-center">
          <div
            id="speakers"
            className="relative flex flex-col items-center justify-center pt-20 lg:pt-8"
          >
            <div className="text-center">
              <div className="flex items-center justify-center">
                <div className="text-lg sm:text-sm text-white font-semi-bold border-b-2 border-blue-400 mb-1">
                  Cast
                </div>
              </div>
            </div>
            <Heading
              typeStyle="heading-md"
              className="text-gradient text-center lg:mt-10"
            >
              Un cast 100% féminin
            </Heading>
            <div className="max-w-3xl sm:w-full text-center">
              <Paragraph
                typeStyle="body-lg"
                className="mt-6"
                textColor="text-gray-200"
              >
                Joueuses et streameuses récurrentes de la scène francophone
              </Paragraph>
            </div>
            <div className="lg:py-20 w-[1130px] lg:w-full">
              <div className="mt-[64px] pb-[181px] lg:pb-[80px]">
                {speakersList.length > 0 ? (
                  <div className="w-full grid grid-cols-3 lg:grid-cols-2 sm:grid-cols-1 gap-4">
                    {speakersList.map((speaker) => {
                      return (
                        <Speaker
                          key={speaker.id}
                          details={speaker}
                          location={
                            currentCity.name !== 'All'
                              ? `${currentCity.name}, ${currentCity.country}`
                              : speaker.city[1]
                                ? `${speaker.city[0]} & ${speaker.city[1]}`
                                : `${speaker.city[0]}`
                          }
                          className="mt-10"
                        />
                      );
                    })}
                  </div>
                ) : (
                  <div className="mt-[64px] pb-[181px] flex items-center justify-center text-center">
                    <div className="w-[720px] lg:w-full">
                      {typeof currentCity !== 'string' && currentCity.cfp ? (
                        <div>
                          <Paragraph className="text-gray-200">
                            We are actively accepting speaker applications, and
                            you can start your journey by clicking the button
                            below. Join us on stage and share your valuable
                            insights with our enthusiastic audience!
                          </Paragraph>
                          <Link legacyBehavior href={currentCity.cfp}>
                            <a className="flex justify-center" target="_blank">
                              <Button
                                type="button"
                                className="mt-[80px] w-[244px] border border-gray"
                              >
                                Apply as a speaker
                              </Button>
                            </a>
                          </Link>
                        </div>
                      ) : (
                        <div>
                          <Heading
                            typeStyle="heading-md-semibold"
                            className="text-gray-200"
                          >
                            {typeof currentCity !== 'string' &&
                              currentCity.name}{' '}
                            Speakers Coming Soon - Stay Tuned!
                          </Heading>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="register" className="container mt-20 lg:mt-0">
        <div className="flex items-center flex-col justify-center">
          <div
            id="teams"
            className="relative flex flex-col items-center justify-center pt-20 lg:pt-8"
          >
            <div className="text-center">
              <div className="flex items-center justify-center">
                <div className="text-lg sm:text-sm text-white font-semi-bold border-b-2 border-blue-400 mb-1">
                  Equipes
                </div>
              </div>
            </div>
            <Heading
              typeStyle="heading-md"
              className="text-gradient text-center lg:mt-10"
            >
              Des équipes au rendez-vous
            </Heading>
            <div className="max-w-3xl sm:w-full text-center">
              <Paragraph
                typeStyle="body-lg"
                className="mt-6"
                textColor="text-gray-200"
              >
                Tout niveau et de plusieurs nationalités
              </Paragraph>
            </div>
            <div className="lg:py-20 w-[1130px] lg:w-full">
              <div className="mt-[64px] pb-[181px] lg:pb-[80px]">
                {teamsList.length > 0 ? (
                  <div className="w-full grid grid-cols-3 lg:grid-cols-2 sm:grid-cols-1 gap-4">
                    {teamsList.map((team) => {
                      return (
                        <Speaker
                          key={team.id}
                          details={team}
                          location={
                            currentCity.name !== 'All'
                              ? `${currentCity.name}, ${currentCity.country}`
                              : team.city[1]
                                ? `${team.city[0]} & ${team.city[1]}`
                                : `${team.city[0]}`
                          }
                          className="mt-10"
                        />
                      );
                    })}
                  </div>
                ) : (
                  <div className="mt-[64px] pb-[181px] flex items-center justify-center text-center">
                    <div className="w-[720px] lg:w-full">
                      {typeof currentCity !== 'string' && currentCity.cfp ? (
                        <div>
                          <Paragraph className="text-gray-200">
                            We are actively accepting speaker applications, and
                            you can start your journey by clicking the button
                            below. Join us on stage and share your valuable
                            insights with our enthusiastic audience!
                          </Paragraph>
                          <Link legacyBehavior href={currentCity.cfp}>
                            <a className="flex justify-center" target="_blank">
                              <Button
                                type="button"
                                className="mt-[80px] w-[244px] border border-gray"
                              >
                                Apply as a speaker
                              </Button>
                            </a>
                          </Link>
                        </div>
                      ) : (
                        <div>
                          <Heading
                            typeStyle="heading-md-semibold"
                            className="text-gray-200"
                          >
                            {typeof currentCity !== 'string' &&
                              currentCity.name}{' '}
                            Speakers Coming Soon - Stay Tuned!
                          </Heading>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
          <div
            id="tickets"
            className="flex items-center flex-col justify-center pt-20 lg:pt-0"
          >
            <div className="text-lg sm:text-sm text-white font-semi-bold border-b-2 border-blue-400 mb-1">
              Live
            </div>
            <div
              data-test="ticket-section"
              className="flex flex-col items-center "
            >
              <Heading
                typeStyle="heading-md"
                className="text-gradient text-center lg:mt-10"
              >
                Suivre la compétition
              </Heading>
              <div className="max-w-3xl sm:w-full text-center">
                <div id="contact" className="container mt-20 lg:mt-0">
                  <div className="flex items-center flex-col justify-center">
                    <div className="text-lg sm:text-sm text-white font-semi-bold border-b-2 border-blue-400 mb-1">
                      Contact
                    </div>
                    <Heading
                      typeStyle="heading-md"
                      className="text-gradient text-center lg:mt-10"
                    >
                      Nous contacter
                    </Heading>
                    <div id="contact" className="container mt-20 lg:mt-0">
                      <div className="flex items-center flex-col justify-center">
                        <div className="text-lg sm:text-sm text-white font-semi-bold border-b-2 border-blue-400 mb-1">
                          Contact
                        </div>
                        <Heading
                          typeStyle="heading-md"
                          className="text-gradient text-center lg:mt-10"
                        >
                          Nous contacter
                        </Heading>

                        <div className="max-w-2xl w-full mt-10">
                          {/* 
              POINTS CLEFS POUR NETLIFY :
              - name="contact" (identifie le formulaire)
              - method="POST" et data-netlify="true" (détection)
              - netlify-honeypot="bot-field" + input hidden (anti-bot)
              - input hidden form-name (obligatoire)
            */}

                          <form
                            name="contact"
                            method="POST"
                            data-netlify="true"
                            netlify-honeypot="bot-field"
                            onSubmit={handleSubmit}
                            className="flex flex-col space-y-6 bg-gray-900 p-8 rounded-2xl shadow-lg"
                          >
                            {/* champs cachés requis */}
                            <input
                              type="hidden"
                              name="form-name"
                              value="contact"
                            />
                            <p className="hidden">
                              <label>
                                Ne pas remplir : <input name="bot-field" />
                              </label>
                            </p>

                            <div>
                              <label className="block text-gray-300 mb-2">
                                Nom
                              </label>
                              <input
                                type="text"
                                name="name"
                                required
                                className="w-full p-3 rounded-md bg-gray-800 border border-gray-700 text-white focus:border-blue-400 focus:outline-none"
                                placeholder="Votre nom"
                              />
                            </div>

                            <div>
                              <label className="block text-gray-300 mb-2">
                                Email
                              </label>
                              <input
                                type="email"
                                name="email"
                                required
                                className="w-full p-3 rounded-md bg-gray-800 border border-gray-700 text-white focus:border-blue-400 focus:outline-none"
                                placeholder="Votre adresse email"
                              />
                            </div>

                            <div>
                              <label className="block text-gray-300 mb-2">
                                Message
                              </label>
                              <textarea
                                name="message"
                                rows={5}
                                required
                                className="w-full p-3 rounded-md bg-gray-800 border border-gray-700 text-white focus:border-blue-400 focus:outline-none"
                                placeholder="Votre message..."
                              />
                            </div>

                            <button
                              type="submit"
                              disabled={sending}
                              className={`bg-blue-500 hover:bg-blue-600 text-white font-semibold py-3 px-6 rounded-md transition-colors duration-200 ${sending ? 'opacity-70 cursor-not-allowed' : ''}`}
                            >
                              {sending ? 'Envoi en cours…' : 'Envoyer'}
                            </button>

                            {sent === 'ok' && (
                              <p className="text-green-400 text-sm">
                                Merci pour votre message !
                              </p>
                            )}
                            {sent === 'err' && (
                              <p className="text-red-400 text-sm">
                                Échec de l’envoi : {errMsg}
                              </p>
                            )}
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="sponsors" className="mt-20">
        <Sponsors
          eventSponsors={[
            {
              image: '/img/logos/apidays.png',
              websiteUrl: 'https://www.apidays.global/',
            },
            {
              image: '/img/logos/APICONF-LOGO-White.png',
              websiteUrl: 'https://apiconf.net/',
            },
          ]}
          financialSponsor={[
            {
              image: '/img/logos/IBM.png',
              websiteUrl: 'https://www.ibm.com/',
            },
            {
              image: '/img/logos/graviteeio-logo.webp',
              websiteUrl: 'https://www.gravitee.io/',
            },
          ]}
        />
      </div>
      <div className="mt-5">
        <Subscription />
      </div>
    </div>
  );
}
